services:

  backend:
    build: ./app
    restart: always
    links:
      - db
    ports:
      - "3000"
    environment:
      - DB_NAME=training
      - DB_HOST=db
      - DB_USER=peserta
      - DB_PASS=password
      - APP_PORT=3000
    volumes:
      - app-data:/app/public/images
    networks:
      - simple-apps

  db:
    image: "mariadb"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=training
      - MYSQL_USER=peserta
      - MYSQL_PASSWORD=password
    volumes:
      - ./app/database/:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    networks:
      - simple-apps

volumes:
  app-data:
  db-data:
  
networks:  
proxy:
  external: true
  simple-apps:
